### ISSUE TITLE
能识别搜狗输入法通过 shift 切换的中英文的状态吗？

### ISSUE THREAD

**Issue by GanZhiXiong** [Yang-Xijie/InputSourceSwitcher#17]
[搜狗输入法 for Mac - 支持全拼、双拼、模糊输入、苹果输入、云输入](https://pinyin.sogou.com/mac/) 这一个输入法，在需要使用英文时，我使用 shift 来切换（搜狗支持通过配置 shift 切换中英文），而不是使用系统的英文输入法。

你软件能获取搜狗的英文状态吗？因为你软件似乎是把搜狗中英文状态当成了一种，因此只能给搜狗输入法设置一个快捷键，而不能指定搜狗输入法的中文和英文分别设置快捷键。

**Comment by GanZhiXiong** [comment]
[搜狗输入法 for Mac - 支持全拼、双拼、模糊输入、苹果输入、云输入](https://pinyin.sogou.com/mac/) 这一个输入法，在需要使用英文时，我使用 shift 来切换（搜狗支持通过配置 shift 切换中英文），而不是使用系统的英文输入法。

你软件能获取搜狗的英文状态吗？因为你软件似乎是把搜狗中英文状态当成了一种，因此只能给搜狗输入法设置一个快捷键，而不能指定搜狗输入法的中文和英文分别设置快捷键。

**Comment by Yang-Xijie** [comment]
目前这个软件是只对系统的输入法生效的。
你说的情况是切换了默认的输入法，软件无法获取对应的信息
