### ISSUE TITLE
作者停止维护这个项目，那有没有替代 App 或其他方案？

### ISSUE THREAD

**Issue by GanZhiXiong** [Yang-Xijie/InputSourceSwitcher#20]
通过 Applescript 去操作菜单栏的输入法进行切换这种方式总感觉体验不好：
- UI 操作会有延迟。
- 切换时会显示输入法菜单列表，如下图所示，这样的视觉体验差。
![image](https://user-images.githubusercontent.com/27394631/150689745-d2e48df6-dbe6-4334-b6cb-73467ba30c6a.png)

**Comment by Yang-Xijie** [comment]
我感觉现在的情况是macOS 12的bug，说不定什么时候苹果就修了
我不推荐你现在用这个app，替代方案你可以试一下[kawa](https://github.com/hatashiro/kawa)，我现在正在用，功能是完美的。

你也可以去看这一条讨论获取更多信息
https://github.com/Yang-Xijie/InputSourceSwitcher/discussions/19
