### ISSUE TITLE
The about window should only show on first run

### ISSUE THREAD

**Issue by zcbenz** [Yang-Xijie/InputSourceSwitcher#3]
I set the app to run on login, and the about window shows every time when the app is opened. It should only show when the app runs for the first time.

**Comment by zcbenz** [comment]
Hmm I just saw https://github.com/Yang-Xijie/InputSourceSwitcher/commit/ee8724db8c8572542b100053967ce5e84f6b6ebf but it does not seem to work.

**Comment by Yang-Xijie** [comment]
Optimize AboutView logic in a7120998f95d26c9b6b75194359d468b65e78cad and you can download the [release v1.0.2](https://github.com/Yang-Xijie/InputSourceSwitcher/releases/tag/v1.0.2).

**Comment by Yang-Xijie** [comment]
Updated it in 373464c8b2dcb581e45b087df95679bf6df44abe.

Thanks for advice!
