### ISSUE TITLE
The dock icon should be hidden

### ISSUE THREAD

**Issue by zcbenz** [Yang-Xijie/InputSourceSwitcher#4]
The menubar apps generally do not have dock icons. App should only have dock icons when it has a main window to show, otherwise giving focus to the app is meaningless.

This app only has one about window, which users usually do not want to see.

**Comment by Yang-Xijie** [comment]
Have a point! Thanks for this advice.

I will **integrate AboutView into the menu bar pop over** and add a toggle bool to show `About` and `Hide About`.

**Comment by Yang-Xijie** [comment]
Updated in a7120998f95d26c9b6b75194359d468b65e78cad and you can download the [release v1.0.2](https://github.com/Yang-Xijie/InputSourceSwitcher/releases/tag/v1.0.2).
