### ISSUE TITLE
⌘I "About" tab is broken with overflown Input Sources

### ISSUE THREAD

**Issue by GJRobert** [Yang-Xijie/InputSourceSwitcher#7]
First of all, applause for this new method to switch input sources without irritation! Kawa has add a forced "Switching to US first" method to overcome CJKV problem, but Source Switcher is doing more neatly.

This is the only graphical glitch I have found:
<img width="427" alt="Source Switcher About tab glitch" src="https://user-images.githubusercontent.com/655584/126595073-2a75895e-7af1-47db-ab00-69e1de885780.png">

Steps to reproduce:
* Press About in the main dropdown menu of Source Switcher
* The space above the introduction of the app is broken by too many input sources (I have 15...)
* ⌘I toggles between the broken view and the main menu

**Comment by Yang-Xijie** [comment]
Currently, I fix the max input sources to six, for I don't think one could use more than six input sources. This make the menu bar app have a simple layout.

Maybe sometime I will consider about it. Or pull requests are welcome!

**Comment by Yang-Xijie** [comment]
https://github.com/Yang-Xijie/InputSourceSwitcher/blob/10906df7dd16eedcdb095954c769eba9657ae1c7/InputSourceSwitcher/App/ContentView.swift#L20

If you want to change the frame height, just change the concerning codes, and rebuild the app by yourself.

**Comment by Yang-Xijie** [comment]
https://github.com/Yang-Xijie/InputSourceSwitcher/blob/91af6aead7f9c4a20be02f2a60c05d4cdbe77e46/InputSourceSwitcher/App/ContentView.swift#L12-L22

Thanks for your report! I have fixed this issue in version 1.1 (5) and you can download the app from the release page.

https://github.com/Yang-Xijie/InputSourceSwitcher/releases/tag/v1.1

**Comment by GJRobert** [comment]
Thank you so much for your kind help! This is such a great tool!
